# Servicios de la aplicaci√≥n
services:
  # Servicio de la API REST
  # comentar si no se quiere ejecutar en local o IDE
  tienda-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda-api-rest
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - storage-dir:/app/storage-dir
    networks:
      - tienda-network

# Volume para guardar los datos de la base de datos
volumes:
  storage-dir:

networks:
  tienda-network:
    driver: bridge