version: '3.8'
# Servicio de la API REST
services:
  # MongoDB
  mongo:
    container_name: pedidos-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/tienda.js:/docker-entrypoint-initdb.d/tienda.js:ro

    # Mongo Express para conectarse a la base de datos
    # Quitar en producci√≥n
  mongo-express:
    container_name: pedidos-db_mongo-express
    image: mongo-express
    restart: always
    env_file: .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo